name: Create Changelog PR

on:
  pull_request:
    types: [closed]

jobs:
  changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # needed to push a new branch

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Set variables
        id: vars
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          BRANCH_NAME="changelog/pr-${PR_NUMBER}"
          echo "entry=${PR_TITLE} #${PR_NUMBER}" >> $GITHUB_OUTPUT
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Create and switch to new branch
        run: |
          git checkout -b ${{ steps.vars.outputs.branch }}

      - name: Add changelog entry
        run: |
          ENTRY="${{ steps.vars.outputs.entry }}"
          FILE="changelog.md"

          awk -v entry="$ENTRY" '
            BEGIN { inserted = 0 }
            {
              print $0
              if (!inserted && /^Unpublished$/) {
                getline;  # Expecting 'Changed'
                print $0
                print entry
                inserted = 1
              }
            }
          ' "$FILE" > tmp && mv tmp "$FILE"

      - name: Commit changes
        run: |
          git add changelog.md
          git commit -m "chore: add changelog for #${{ github.event.pull_request.number }}"

      - name: Push branch
        run: |
          git push --set-upstream origin ${{ steps.vars.outputs.branch }}

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ steps.vars.outputs.branch }}
          title: "chore: changelog entry for #${{ github.event.pull_request.number }}"
          body: "This PR adds a changelog entry for #${{ github.event.pull_request.number }}.\n\nPlease review or edit as needed."
