name: Require Changelog Entry

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0 # Ensure previous commit is available for git commands

      - name: Check for changelog entry
        run: |
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"

          if git diff --name-only $BASE_SHA $HEAD_SHA | grep -q "^changelog.md$"; then
            echo "✅ Changelog entry found!"
          else
            echo "❌ No changelog.md entry found"
            exit 1
          fi
