name: Require Changelog Entry

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure changelog.md was modified in this PR
        if: github.event_name == 'pull_request'
        run: |
          # Fetch the list of changed files in the PR
          CHANGED_FILES=$(gh pr view ${{ github.event.pull_request.number }} --json files -q '.files[].path')
          if echo "$CHANGED_FILES" | grep -qx "changelog.md"; then
            echo "✅ Changelog entry found!"
          else
            echo "❌ No changelog.md entry found"
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  changelog_exemption:
    needs: check-changelog
    if: failure()  # Only runs if the previous job failed
    runs-on: ubuntu-latest
    environment:
      name: changelog-exemption
    steps:
      - name: Await contributor approval for changelog exemption
        run: echo "Changelog missing - awaiting exemption approval by contributor."
