name: Require Changelog Entry

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.check.outputs.updated }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure changelog.md was modified in this PR
        if: github.event_name == 'pull_request'
        run: |
          # Fetch the list of changed files in the PR
          CHANGED_FILES=$(gh pr view ${{ github.event.pull_request.number }} --json files -q '.files[].path')
          if echo "$CHANGED_FILES" | grep -qx "changelog.md"; then
             echo "updated=true" >> $GITHUB_OUTPUT            
          else
            echo "updated=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  changelog-exemption:
    needs: check-changelog
    if: needs.check-changelog.outputs.updated == 'false'  # Only runs if the previous job failed
    runs-on: ubuntu-latest
    environment:
      name: changelog-exemption
    steps:
      - name: Await contributor approval for changelog exemption
        run: echo "Changelog missing - awaiting exemption approval by contributor."

  final-status:
    needs: [check-changelog, changelog-exemption]
    runs-on: ubuntu-latest
    if: |
      needs.check-changelog.outputs.updated == 'true' ||
      (needs.check-changelog.outputs.updated == 'false' && needs.changelog-exemption.result == 'success')
    steps:
      - name: Mark workflow as successful
        run: echo "Changelog updated, or exemption granted"

