name: Require Changelog Entry

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check-changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check for changelog entry
        run: |
          if git log origin/master..HEAD --name-only --pretty="" | grep -q "^changelog.md$"; then
            echo "Changelog entry found ✅"
          else
            echo "❌ No changelog.md entry found"
            exit 1
          fi
