name: Require Changelog Entry

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.check.outputs.updated }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure changelog.md was modified in this PR
        id: check
        if: github.event_name == 'pull_request'
        run: |
          # Fetch the list of changed files in the PR
          CHANGED_FILES=$(gh pr view ${{ github.event.pull_request.number }} --json files -q '.files[].path')
          if echo "$CHANGED_FILES" | grep -qx "changelog.md"; then
             echo "updated=true" >> $GITHUB_OUTPUT
             echo "✅ Changelog entry found!"
          else
            echo "updated=false" >> $GITHUB_OUTPUT
            echo "❌ No changelog.md entry found"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  changelog-missing-exemption:
    needs: check-changelog
    runs-on: ubuntu-latest
    environment:
      name: Request for changelog entry exemption
    steps:
      - name: Check changelog status
        run: |
          if [[ "${{ needs.check-changelog.outputs.updated }}" == "true" ]]; then
            echo "✅ Changelog entry found!"
          else
            echo "❌ Changelog entry missing - awaiting exemption approval by contributor."
          fi
